# Generated by Django 5.1.5 on 2025-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_name',
            field=models.CharField(default='None', max_length=256),
        ),
    ]
